import type { Metadata } from "next";
import { Roboto } from "next/font/google";
// import { ThemeAppProvider } from "@/components/ThemeAppProvider";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const roboto = Roboto({
	variable: "--font-roboto-sans",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "MN Labs technology",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={roboto.variable}>
			<head>
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/logo_mn.png" />
			</head>
			<body className="antialiased dark " cz-shortcut-listen="true">
				<ThemeProvider defaultTheme="system">{children}</ThemeProvider>
			</body>
		</html>
	);
}
